import type { Config } from 'tailwindcss';

/**
 * Design tokens exported from the Stitch templates (Material-3 style palette,
 * Inter + Plus Jakarta Sans type ramp, spacing scale). Kept verbatim so every
 * utility class used in the mockups renders identically here.
 */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#311fca',
        'on-secondary-fixed': '#002114',
        'surface-variant': '#dae2fd',
        'on-primary-container': '#cad3ff',
        'tertiary-fixed': '#e2dfff',
        primary: '#0037b0',
        'on-tertiary-fixed-variant': '#3323cc',
        'primary-container': '#1d4ed8',
        'primary-fixed': '#dce1ff',
        'on-secondary-container': '#00714e',
        'on-tertiary-fixed': '#0f0069',
        'primary-fixed-dim': '#b7c4ff',
        surface: '#faf8ff',
        'on-tertiary-container': '#d3d1ff',
        'inverse-on-surface': '#eef0ff',
        background: '#faf8ff',
        'on-error': '#ffffff',
        'on-primary-fixed': '#001551',
        'tertiary-container': '#4b41e1',
        'on-error-container': '#93000a',
        'surface-bright': '#faf8ff',
        error: '#ba1a1a',
        'outline-variant': '#c4c5d7',
        'surface-tint': '#2151da',
        outline: '#747686',
        'secondary-container': '#82f5c1',
        'on-primary-fixed-variant': '#0039b5',
        secondary: '#006c4a',
        'surface-container-low': '#f2f3ff',
        'on-background': '#131b2e',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#c3c0ff',
        'secondary-fixed': '#85f8c4',
        'inverse-primary': '#b7c4ff',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#68dba9',
        'on-surface': '#131b2e',
        'surface-dim': '#d2d9f4',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#005137',
        'on-surface-variant': '#434655',
        'surface-container-high': '#e2e7ff',
        'on-secondary': '#ffffff',
        'surface-container': '#eaedff',
        'inverse-surface': '#283044',
        'surface-container-highest': '#dae2fd',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-lg': '1.5rem',
        'margin-sm': '1rem',
        margin: '2rem',
        'space-sm': '0.5rem',
        'gutter-sm': '1rem',
        'space-xl': '2rem',
        'space-xs': '0.25rem',
        'margin-lg': '3rem',
        gutter: '1.5rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'label-prominent': ['Inter', 'sans-serif'],
        'label-tag': ['Inter', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-card': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'salary-metric': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'caption-micro': ['Inter', 'sans-serif'],
        'display-hero-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-prominent': ['13px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-tag': ['12px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'title-card': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'salary-metric': ['19px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'caption-micro': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      boxShadow: {
        xs: '0 1px 2px rgba(19, 27, 46, 0.05)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        shimmer: { '0%': { backgroundPosition: '-400px 0' }, '100%': { backgroundPosition: '400px 0' } },
      },
      animation: {
        'fade-in': 'fade-in 0.25s ease-out',
        shimmer: 'shimmer 1.4s linear infinite',
      },
    },
  },
  plugins: [],
} satisfies Config;
